/*
-- The following is based on KnowTech Submission Registry

	[SubmissionID]         - ISE Prefixed ID Unique Submission Identifier.  Example: "SB201612281009000001"
	[IncidentID]           - ISE Prefixed ID Unique Incident Identifier.  Example: "IN201612281009000001"
	[SubmissionDate]       - Submission Date when the message package was submitted by the original agency.
	[ReceiveDate]          - Submission when the message package was received.
	[MessageDateTime]      - Date and Time of the message was prepared.
	[ContentType]          - Submission message content (payload) type, for example:  CFS-CREATE; CFS-UPDATE; CFS-CLOSE; CFS-TRANSFER; USU; RFR; RUSU;
	[SourceAgencyID]       - SourceAgencyID is the SubmitterID that identifies the agency that sends the information. This ID may be different from the agency data owner who owns the data.  Example: MLPFD - Milpitas Police Fire Dept.
	[SourceLocalID]        - This is the Local Id for the Service Call as generated by the source CAD Application.  Example: For CAD CFS - local id is a unique id for the service call on the source CAD Application (e.g. "LPD161101000099", or "FFD161101008778")
	[DataOwnerAgencyID]    - Data Owner ID  Example CAPSS has data from 4 agencies.  This is the Data Owner ID.  DataOwnerAgencyID to identify the source repository from where the data was and is registered, updated and maintained.   Santa Cruz Agency does submissions for other agencies same as CAPPS. To be reviewed if we need to remove it. SCPD - Data Owner Id MLPPD - Data Owner Id 
	[DataItemID]           - This is the unique identifier to the Payload content. This is the ID which is coming from the agency and is unique to the payload content.
	[MessageData]          - Message CLOB.
	[MessageLengthInBytes] - Length of message (BLOB) in Bytes.
	[MessageCount]         - Number of times this submission has been submitted.  This count helps to identify issues with multiple identical submissions being received by anyone source.
	[ContentReferenceID]   - Each Submission will contain details about one or more pertinent Data Entity (e.g. CFS, USU, Incident Arrest, Jail Release or other) and based on the Content Type (again CFS, USU, other) there will be one Activity identifier that stands up as the representative Data Entity, for example: for the CFS Create it will be the assigned Global-ID. This column contain those representative Data Entity Unique reference ID's.  Based on the Content each Reference ID will have a different form, here are some examples:  - CFS - ServiceCallAugmentation.GlobalCallServiceNumber - For example: "GL201701301151000001"  - for an Incident Arrest you may identify it using the "BookingID", and you will use this as your ContentReferenceID;     In the case that no particular "Data Entity" Reference ID can be identified an ISE Generated ID may be generated instead in the following format: "GL201701041051000001".
 */

CREATE TABLE [Message].[Submission]
(
	[Submission_ID] varchar(20) NOT NULL,
	[IncidentID] varchar(20) NULL,
	[Submission_DateTime] datetime2(7) NOT NULL,
	[ReceiveDate] datetime2(7) NOT NULL,
	[MessageDateTime] datetime2(7) NOT NULL,
	[ContentType] varchar(20) NOT NULL,
	[SourceAgencyID] varchar(20) NOT NULL,
	[SourceLocalID] varchar(20) NOT NULL,
	[DataOwnerAgencyID] varchar(20) NOT NULL,
	[DataItemID] varchar(50) NOT NULL,
	[MessageData] varchar(max) NOT NULL,
	[MessageLengthInBytes] int NOT NULL,
	[MessageCount] int NOT NULL,
	[ContentReferenceID] varchar(20) NULL,

   -- record management
   [Tenant_ID]             VARCHAR(30) NULL DEFAULT 'COMMON',
   [Data_Owner_ID]         VARCHAR(30) NULL DEFAULT 'COMMON',
   [Agency_Reporting_ID]   VARCHAR(30) NULL,
   [Sequence_Number]       INTEGER NULL DEFAULT 0,
   [Efective_DateTime]     DATETIMEOFFSET NULL DEFAULT getutcdate(),
   [Efective_End_DateTime] DATETIMEOFFSET NULL,
   [Version_Number]        VARCHAR(20) NULL DEFAULT '0',
   [Created_DateTime]      DATETIMEOFFSET NULL DEFAULT getutcdate(),
   [Updated_Last_DateTime] DATETIMEOFFSET NULL DEFAULT getutcdate(),
   [Record_Status_Code_ID] CHAR(1) NULL DEFAULT 'A',
   [Session_Updated_ID]    VARCHAR(40) NULL DEFAULT 'E4D32AEC-E7C8-426C-94A6-F0B37F626E67',

   CONSTRAINT [pk_Report] PRIMARY KEY CLUSTERED ([Report_ID] ASC)
)
GO

